version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: blogdb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

    adminer:
        image: adminer:latest
        container_name: adminer
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        ports:
            - "8080:8080"
        restart: always

volumes:
    postgres_data:
